### ISSUE TITLE
Expose APIserver duration metrics and enable logs analytic

### ISSUE THREAD

**Issue by felix-zhe-huang** [awslabs/kubernetes-iteration-toolkit#171]
Our customer would like us to provide the following features:

- Expose the APIserver request duration metrics through Prometheus.
- Enable log data analytics

By default APIserver metrics endpoints exposes `apiserver_request_duration_seconds_bucket`, however, such metrics are not shown in Prometheus. This is likely due to the fact that prometheus add-on helm chart is configured to disable apiserver scraping. How do we enable apiserver scraping for guest cluster will be the tricky part.

To support log analytics, the kit substrate should also deploy ELK stack to collect logs and provide elasticsearch for data analysis.

**Comment by prateekgogia** [comment]
> Expose the APIserver request duration metrics through Prometheus.

This already configured here when you deploy a KIT cluster-
https://github.com/awslabs/kubernetes-iteration-toolkit/blob/main/operator/pkg/controllers/master/podmonitors.go#L29
Let me know if its not working as intended.

Exporting logs is tracked as part of https://github.com/awslabs/kubernetes-iteration-toolkit/issues/106
