### ISSUE TITLE
KIT Environment needs pirvate subnets to support fargate pods

### ISSUE THREAD

**Issue by hakuna-matatah** [awslabs/kubernetes-iteration-toolkit#195]
While I was testing KIT Environment with Fargate, I couldn't create fargate profiles as our KIT environment only creates public subnets even though some subnets are named private, as they have IGW associated in their route tables. Fix is required to be able to launch fargate pods.

```
An error occurred (InvalidParameterException) when calling the CreateFargateProfile operation: Subnet subnet-0ab49c01946ecc462 provided in Fargate Profile is not a private subnet
```

**Comment by prateekgogia** [comment]
Merged
