### ISSUE TITLE
KIT Env today roughly allows less than 500 nodes for eks guest clusters due VPC Subnet limitations 

### ISSUE THREAD

**Issue by hakuna-matatah** [awslabs/kubernetes-iteration-toolkit#198]
Today we only have 1250 IPs in the VPC created by KIT ENV, this is not enough if you want to have more than 250 nodes or so on guest cluster.
This causes serious limitation not only for megaXL but for any clusters wanting to have more than 250 eks nodes
Also, it limits Fargate nodes/pods at around 750 today.

We need to make the VPC bigger to support such usecases for customers

**Comment by prateekgogia** [comment]
This is merged right?

**Comment by hakuna-matatah** [comment]
closing it as it's solved.
