### ISSUE TITLE
[operator] fails to find subnet for DP when CP instance launches on a public subnet

### ISSUE THREAD

**Issue by prateekgogia** [awslabs/kubernetes-iteration-toolkit#232]
When creating dataplane nodes, operator discovers the subnets if no subnet selector is provided. 
For the discovery, it finds the instance ID on which guest control plane is running and finds the subnets associated with these instances. From the subnet IDs found, it then filters for private subnet ID. If the CP instance is associated with public subnet(s), it fails to find any subnet and dataplane node creation fails.

**Comment by rschalo** [comment]
Resolved with the above PR
