### ISSUE TITLE
Allow to pass in InstanceProfile for Dataplane nodes

### ISSUE THREAD

**Issue by njtran** [awslabs/kubernetes-iteration-toolkit#242]
eI want to enable the nodes that are created for the Dataplane to have more policies than the ones defined in the [iam reconciler](https://github.com/awslabs/kubernetes-iteration-toolkit/blob/main/operator/pkg/awsprovider/iam/reconciler.go#L44-L47). This could be in the form of additional policies to add to the existing list, or allowing to provide an Instance Profile ARN myself. 

I only need this as a workaround for IRSA, so this might not be necessary with IRSA.

**Comment by prateekgogia** [comment]
Added the instanceProfile field as part of this PR-
https://github.com/awslabs/kubernetes-iteration-toolkit/pull/286
