### ISSUE TITLE
kitctl can't reconcile a previous bootstrap

### ISSUE THREAD

**Issue by mengqiy** [awslabs/kubernetes-iteration-toolkit#332]
If `kitctl bootstrap` fails in a earlier run, re-run `kitctl bootstrap` should pick up from where it left and reconcile. This desired behavior is broken now.

We wait [here](https://github.com/awslabs/kubernetes-iteration-toolkit/blob/f08d66848d81a1abcb12f9f6c855cd202ac71889/substrate/pkg/controller/substrate/cluster/config.go#L77-L79) until `APIServerAddress` and `MasterInstanceID` are populated.
It appears we only populate this field when we create a new instance [here](https://github.com/awslabs/kubernetes-iteration-toolkit/blob/f08d66848d81a1abcb12f9f6c855cd202ac71889/substrate/pkg/controller/substrate/cluster/instance.go#L91).
But when we reuse an instance [here](https://github.com/awslabs/kubernetes-iteration-toolkit/blob/f08d66848d81a1abcb12f9f6c855cd202ac71889/substrate/pkg/controller/substrate/cluster/instance.go#L46-L48), we actually never populate `MasterInstanceID` field.
 It cause the reconciliation to hang forever.

**Comment by mengqiy** [comment]
@Ganiredi Can you please take a look and fix it?

**Comment by prateekgogia** [comment]
Fixed by - https://github.com/awslabs/kubernetes-iteration-toolkit/pull/339
