### ISSUE TITLE
Installing chart timeout when run kitctl bootstrap

### ISSUE THREAD

**Issue by mengqiy** [awslabs/kubernetes-iteration-toolkit#333]
The default timeout for installing helm chart as addon is 180s. It appears sometimes take longer than that. The pods created by the charts are eventually up and running.
We should increase the timeout or investigate why it sometimes (it happens pretty often to me) takes longer.

**Comment by mengqiy** [comment]
This issue with https://github.com/awslabs/kubernetes-iteration-toolkit/issues/332 makes bootstrapping a kitctl environment pretty painful and time consuming.

**Comment by prateekgogia** [comment]
This should be fixed by https://github.com/awslabs/kubernetes-iteration-toolkit/pull/339
