### ISSUE TITLE
Guest dataplane reconciler unable to retrieve the security group ID

### ISSUE THREAD

**Issue by Ganiredi** [awslabs/kubernetes-iteration-toolkit#379]
Found  error in the kit-controller  logs ,when attempting to provision the guest dataplane nodes. Specifically, the auto scaling group creation for guest-1-21 is failing due to a validation error, with the message indicating that the security group ID sg-05360b23cfd2918b5 does not exist. This error can be seen in the logs. The related Github workflow for this issue can be found at https://github.com/Ganiredi/kubernetes-iteration-toolkit/actions/runs/4248048984/jobs/7386765537.

```2023-02-23T00:05:55.909Z	ERROR	controller.dataplane	Reconciler error	{"reconciler group": "kit.k8s.sh", "reconciler kind": "DataPlane", "name": "guest-1-21-n", "namespace": "default", "error": "reconciling resource, creating auto scaling group for guest-1-21, ValidationError: The security group 'sg-05360b23cfd2918b5' does not exist\n\tstatus code: 400, request id: 41ae3ff3-a72c-476b-8514-4b72d7a28b22"}```

**Comment by hakuna-matatah** [comment]
Looks like it's reusing the same cluster-names here - https://github.com/Ganiredi/kubernetes-iteration-toolkit/actions/runs/4248048984/workflow#L47 which can cause issues. Please use the `github.run_id` like discussed offline for guest-clusters as well.
