### ISSUE TITLE
[Operator] Dataplane spec is mandating to have allocationStrategy in the spec

### ISSUE THREAD

**Issue by hakuna-matatah** [awslabs/kubernetes-iteration-toolkit#72]
- Dataplane spec is mandating to have allocationStrategy in the spec. If not provided it will run into the following issue:
 ```
message: "creating auto scaling group for s-9a7d13d2-e635-4418-8852-7d528e66fa69,
      ValidationError: 1 validation error detected: Value '' at 'mixedInstancesPolicy.launchStrategy.onDemandAllocationStrategy'
      failed to satisfy constraint: Member must have length greater than or equal
      to 1\n\tstatus code: 400, request id: 270dd3de-8aa9-4ff2-baeb-81ac9cfd1fd0"
    status: "False"
    type: Active
```

We need to look into why defaulting doesn't work. If we plan to remove defaulting, we need to update the example spec [here](https://github.com/awslabs/kubernetes-iteration-toolkit/blob/main/operator/docs/examples/dataplane.yaml)] with allocation strategy

**Comment by prateekgogia** [comment]
Fixed in https://github.com/awslabs/kubernetes-iteration-toolkit/pull/75
