### ISSUE TITLE
[operator] aws-iam-authenticator DS names needs to be cluster specific

### ISSUE THREAD

**Issue by hakuna-matatah** [awslabs/kubernetes-iteration-toolkit#73]
Because we name  DS `aws-iam-authenticator` server on kit controlplane  as `aws-iam-authenticator`  for each KIT control-plane , it's causing issues such as recycling of authenticator pods (as a result, it's causing high STS and ec2DescibeInstance calls )when we deploy more than one KIT controlplane CRD on host cluster `testbed`. 
We need to have a unique name for each `aws-iam-authenticator` component to prevent such restarts from happening.

```
dev-dsk-hakuna-2c-dfc2b72b % kubectl get ds 
NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                     AGE
aws-iam-authenticator   3         3         3       3            3           kit.k8s.sh/app=s-e74df950-2d04-42c7-9614-af831b0a3ef3-apiserver   3d4h
```
```
dev-dsk-hakuna-2c-dfc2b72b % kubectl get pods -o wide | grep aws-iam-authenticator 
aws-iam-authenticator-frhhh                                       1/1     Running     0          3m41s   10.22.237.119   ip-10-22-237-119.us-west-2.compute.internal   <none>           <none>
aws-iam-authenticator-h55sg                                       1/1     Running     0          3m41s   10.22.127.7     ip-10-22-127-7.us-west-2.compute.internal     <none>           <none>
aws-iam-authenticator-k5x55                                       1/1     Running     0          3m41s   10.22.201.10    ip-10-22-201-10.us-west-2.compute.internal    <none>           <none>
```

**Comment by prateekgogia** [comment]
I don't think it has anything to do with higher STS calls, as they were reported on 11/06 and this issue started recently when there were multiple KIT control plane deployed in a host cluster.

**Comment by hakuna-matatah** [comment]
> I don't think it has anything to do with higher STS calls, as they were reported on 11/06 and this issue started recently when there were multiple KIT control plane deployed in a host cluster.

Regardless of 11/06 issue , this bug leads to higher STS calls and ec2DescibeInstance calls than normal  because of mere effect of constant recycling of the component, which is what I was stating in the description.
