### ISSUE TITLE
[operator] Ability to specify volume type and IOPS through CRD spec for etcd

### ISSUE THREAD

**Issue by hakuna-matatah** [awslabs/kubernetes-iteration-toolkit#87]
- storage is GP2 for etcd with default IOPS KIT operator gives is 100 which is far from the EKS default we have today. No wonder, we run into slow disk issues on etcd. We need ability to mention this from KIT CRD spec.

**Comment by felix-zhe-huang** [comment]
You can assign me.

**Comment by felix-zhe-huang** [comment]
It looks like Karpenter does not support declaration of EBS volume type and IOPS yet. Will summit a PR to karpenter to enable this.
Meanwhile, it means that this task may take longer than expected.
